// GENERATED by tools/gen_leveldata.py — hand-designed level (world units).
// Edit the python script and re-run it rather than editing this file.

public static class LevelData
{
    public struct Plat { public float x, y, w, h, rot;
        public Plat(float x, float y, float w, float h, float rot) { this.x = x; this.y = y; this.w = w; this.h = h; this.rot = rot; } }
    public struct Check { public float x, y; public bool doubleJump, goal;
        public Check(float x, float y, bool dj, bool goal) { this.x = x; this.y = y; doubleJump = dj; this.goal = goal; } }
    public struct Zone { public float x, y, w, h; public string msg;
        public Zone(float x, float y, float w, float h, string msg) { this.x = x; this.y = y; this.w = w; this.h = h; this.msg = msg; } }
    public struct Sign { public float x, y; public string text;
        public Sign(float x, float y, string text) { this.x = x; this.y = y; this.text = text; } }

    public static readonly Plat[] Platforms =
    {
        new Plat(-11.500f, 3.000f, 9.000f, 6.000f, 0f),
        new Plat(29.000f, -3.000f, 34.000f, 6.000f, 0f),
        new Plat(39.000f, 0.650f, 2.000f, 2.300f, 0f),
        new Plat(44.000f, 1.150f, 2.000f, 3.300f, 0f),
        new Plat(66.000f, -5.000f, 32.000f, 6.000f, 0f),
        new Plat(61.500f, -1.000f, 3.000f, 2.000f, 0f),
        new Plat(67.500f, 0.100f, 3.000f, 4.200f, 0f),
        new Plat(81.000f, -1.500f, 18.000f, 13.000f, 0f),
        new Plat(88.000f, 10.125f, 4.000f, 7.750f, 0f),
        new Plat(176.250f, -30.500f, 39.500f, 6.000f, 0f),
        new Plat(185.000f, -26.000f, 22.000f, 3.000f, 0f),
        new Plat(216.000f, -28.500f, 40.000f, 5.000f, 0f),
        new Plat(206.000f, -17.000f, 4.000f, 18.000f, 0f),
        new Plat(218.000f, -14.000f, 4.000f, 24.000f, 0f),
        new Plat(201.750f, -22.100f, 2.500f, 1.200f, 0f),
        new Plat(198.250f, -16.600f, 2.500f, 1.200f, 0f),
        new Plat(201.750f, -11.100f, 2.500f, 1.200f, 0f),
        new Plat(209.250f, -22.600f, 2.500f, 1.200f, 0f),
        new Plat(214.750f, -18.600f, 2.500f, 1.200f, 0f),
        new Plat(209.250f, -14.600f, 2.500f, 1.200f, 0f),
        new Plat(214.750f, -10.600f, 2.500f, 1.200f, 0f),
        new Plat(209.250f, -6.600f, 2.500f, 1.200f, 0f),
        new Plat(242.000f, -7.000f, 44.000f, 10.000f, 0f),
        new Plat(241.000f, 2.625f, 18.000f, 6.750f, 0f),
        new Plat(227.250f, 0.900f, 2.500f, 1.200f, 0f),
        new Plat(291.000f, -13.000f, 54.000f, 6.000f, 0f),
        new Plat(373.000f, -23.250f, 10.000f, 2.500f, 0f),
        new Plat(449.000f, -41.000f, 42.000f, 6.000f, 0f),
        new Plat(-5.794f, 4.229f, 3.059f, 3.000f, -11.31f),
        new Plat(-2.057f, 3.007f, 5.385f, 3.000f, -21.80f),
        new Plat(2.851f, 0.848f, 5.546f, 3.000f, -25.64f),
        new Plat(7.159f, -0.811f, 3.081f, 3.000f, -13.13f),
        new Plat(10.351f, -1.343f, 3.015f, 3.000f, -5.71f),
        new Plat(91.240f, 3.258f, 3.046f, 3.000f, -10.00f),
        new Plat(94.487f, 2.333f, 4.257f, 3.000f, -20.00f),
        new Plat(98.705f, 0.181f, 5.896f, 3.000f, -32.00f),
        new Plat(114.118f, -10.768f, 32.138f, 3.000f, -36.00f),
        new Plat(129.296f, -21.387f, 4.530f, 3.000f, -28.00f),
        new Plat(133.036f, -23.040f, 3.154f, 3.000f, -18.00f),
        new Plat(135.750f, -23.601f, 1.500f, 3.000f, 0.00f),
        new Plat(137.786f, -23.379f, 2.037f, 3.000f, 11.01f),
        new Plat(140.513f, -22.576f, 3.193f, 3.000f, 20.00f),
    };

    public static readonly Check[] Checkpoints =
    {
        new Check(32.000f, 0.000f, false, false),
        new Check(75.000f, 5.000f, false, false),
        new Check(182.000f, -24.500f, true, false),
        new Check(256.000f, -2.000f, false, false),
        new Check(452.000f, -38.000f, false, true),
    };

    public static readonly Zone[] KillZones =
    {
        new Zone(149.500f, -37.000f, 13.000f, 18.000f, "SNIP! Mind the shredder pit..."),
        new Zone(373.000f, 2.500f, 110.000f, 3.000f, "Too high! The shredder sky hums above..."),
        new Zone(475.000f, -26.000f, 6.000f, 40.000f, "The world ends here...\nand I hope you're not trying to run away"),
    };

    public static readonly Sign[] Signs =
    {
        new Sign(-12.000f, 6.000f, "A crumpled little sheet,\na long way from home..."),
        new Sign(16.000f, 0.000f, "You are PAPER.\nA / D to move, SPACE to jump"),
        new Sign(26.000f, 0.000f, "Little one, you can fold!\nX folds you up · Z unfolds you"),
        new Sign(70.500f, -2.000f, "Stuck?\nPress R to return\nto your checkpoint"),
        new Sign(80.000f, 5.000f, "Only a BALL fits down the chute.\nPress X to fold!"),
        new Sign(85.000f, 5.000f, "Roll with it — speed is the\nonly way across the pit"),
        new Sign(168.000f, -27.500f, "Balls can't jump...\nPress Z to unfold into PAPER"),
        new Sign(188.000f, -24.500f, "Press SPACE in mid-air\nto DOUBLE JUMP!"),
        new Sign(211.000f, -26.000f, "Many ways up!\n(Press O to zoom out, I to zoom in)"),
        new Sign(228.000f, -2.000f, "Tight squeeze? Fold into a BALL (X)\n...or find a way OVER"),
        new Sign(302.000f, -10.000f, "Press C in MID-AIR\nto fold into a PLANE!"),
        new Sign(312.000f, -10.000f, "Glide far, sink slow.\n(Z unfolds you anytime — careful!)"),
        new Sign(371.000f, -22.000f, "Rest stop!\nJump + C to take off again\n(skipping it is faster...)"),
        new Sign(458.000f, -38.000f, "You made it!\nA single sheet can become anything ♥"),
    };

    public static readonly float PlayerStartX = -12.000f;
    public static readonly float PlayerStartY = 7.500f;
    public static readonly float GlobalKillY = -52.0f;
}
